"""Deterministic, non-mutating Linux sibling checkpoint patch generation."""

from __future__ import annotations

import difflib
import hashlib
from pathlib import Path
import subprocess

from .generator import (
    Checkpoint,
    CheckpointGenerationError,
    CheckpointMapping,
    _observation_source,
)


def _git(sibling: Path, *arguments: str) -> str:
    result = subprocess.run(
        ["git", *arguments],
        cwd=sibling,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if result.returncode != 0:
        detail = result.stderr.strip() or result.stdout.strip()
        raise CheckpointGenerationError(f"sibling git {' '.join(arguments)} failed: {detail}")
    return result.stdout.strip()


def validate_sibling(sibling: Path, mapping: CheckpointMapping) -> None:
    if not sibling.is_dir():
        raise CheckpointGenerationError(f"sibling path does not exist: {sibling}")
    commit = _git(sibling, "rev-parse", "HEAD")
    if commit != mapping.sibling_commit:
        raise CheckpointGenerationError(
            f"sibling commit {commit} != frozen {mapping.sibling_commit}"
        )
    branch = _git(sibling, "branch", "--show-current")
    if branch != mapping.sibling_branch:
        raise CheckpointGenerationError(
            f"sibling branch {branch!r} != frozen {mapping.sibling_branch!r}"
        )
    status = _git(sibling, "status", "--short")
    if status:
        raise CheckpointGenerationError("sibling worktree is not clean")
    for relative, expected in mapping.sibling_files:
        path = sibling / relative
        try:
            content = path.read_bytes()
        except OSError as exc:
            raise CheckpointGenerationError(f"cannot read sibling anchor {relative}: {exc}") from exc
        observed = hashlib.sha256(content).hexdigest()
        if observed != expected:
            raise CheckpointGenerationError(
                f"sibling anchor fingerprint mismatch for {relative}"
            )


def _c_parameters(item: Checkpoint, *, names: bool = True) -> str:
    return ", ".join(
        f"uint64_t {'arg' + str(index) if names else ''}".rstrip()
        for index, _ in enumerate(item.parameters)
    ) or "void"


def _render_c_declarations(checkpoints: tuple[Checkpoint, ...]) -> str:
    return "\n".join(
        f"extern void {item.symbol}({_c_parameters(item)});" for item in checkpoints
    )


def _c_source(item: Checkpoint, parameter: str) -> str:
    source = _observation_source(item, parameter)
    return source.replace("kernel.", "kernel.").replace("trampoline.", "trampoline.")


def _render_milestone(
    milestone: str, checkpoints: tuple[Checkpoint, ...]
) -> str:
    observation_lines = {
        "kernel_map_ready": (
            "\tstruct lkm2_cp_kernel kernel = lkm2_cp_observe_kernel();\n"
            "\tuint64_t satp = csr_read(CSR_SATP);"
        ),
        "preset_complete": (
            "\tstruct lkm2_cp_kernel kernel = lkm2_cp_observe_kernel();\n"
            "\tuint64_t satp = csr_read(CSR_SATP);"
        ),
        "trampoline_ready": (
            "\tstruct lkm2_cp_trampoline trampoline = lkm2_cp_observe_trampoline();"
        ),
        "early_kernel_ready": (
            "\tstruct lkm2_cp_early_kernel early_kernel = lkm2_cp_observe_early_kernel();"
        ),
        "early_dtb_ready": (
            "\tstruct lkm2_cp_early_dtb early_dtb = lkm2_cp_observe_early_dtb();"
        ),
        "setup_complete": (
            "\tstruct lkm2_cp_kernel kernel = lkm2_cp_observe_kernel();\n"
            "\tstruct lkm2_cp_trampoline trampoline = lkm2_cp_observe_trampoline();\n"
            "\tstruct lkm2_cp_early_kernel early_kernel = lkm2_cp_observe_early_kernel();\n"
            "\tstruct lkm2_cp_early_dtb early_dtb = lkm2_cp_observe_early_dtb();\n"
            "\tuint64_t satp = csr_read(CSR_SATP);"
        ),
    }
    lines = [f"static void __init lkm2_checkpoint_{milestone}(void)", "{", observation_lines[milestone]]
    for item in checkpoints:
        if item.milestone != milestone:
            continue
        arguments = ", ".join(_c_source(item, parameter) for parameter in item.parameters)
        lines.append(f"\t{item.symbol}({arguments});")
    lines.append("}")
    return "\n".join(lines)


def render_linux_include(
    checkpoints: tuple[Checkpoint, ...], mapping: CheckpointMapping
) -> str:
    milestones = "\n\n".join(
        _render_milestone(name, checkpoints) for name in mapping.milestones
    )
    return f"""/* @generated by lkm2 checkpointgen; do not edit. */
#include <linux/types.h>

{_render_c_declarations(checkpoints)}

struct lkm2_cp_kernel {{
	uint64_t kernel_va, kernel_pa, page_offset, kernel_va_pa_offset;
	uint64_t mode, levels, top_shift;
}};

struct lkm2_cp_trampoline {{
	uint64_t mode, va, pa, size, flags, path_ok;
}};

struct lkm2_cp_early_kernel {{
	uint64_t mode, va, pa, flags, coverage_ok;
}};

struct lkm2_cp_early_dtb {{
	uint64_t mode, dtb_pa, dtb_va, fix_va;
	uint64_t leaf0_pa, leaf0_flags, leaf1_pa, leaf1_flags;
	uint64_t size, coverage_ok;
}};

static uint64_t __init lkm2_cp_pte_pa(uint64_t entry)
{{
	return ((entry & _PAGE_PFN_MASK) >> _PAGE_PFN_SHIFT) << PAGE_SHIFT;
}}

static uint64_t __init lkm2_cp_pte_flags(uint64_t entry)
{{
	return entry & 0x3ff;
}}

static bool __init lkm2_cp_table_matches(uint64_t entry, uintptr_t table)
{{
	return lkm2_cp_pte_pa(entry) == table && lkm2_cp_pte_flags(entry) == _PAGE_TABLE;
}}

static uint64_t __init lkm2_cp_walk(pgd_t *root, p4d_t *p4d, pud_t *pud,
				     pmd_t *pmd, uintptr_t va, uint64_t *path_ok)
{{
	uint64_t entry = pgd_val(root[pgd_index(va)]);
	bool ok;

	if (pgtable_l5_enabled) {{
		ok = lkm2_cp_table_matches(entry, (uintptr_t)p4d);
		entry = p4d_val(p4d[p4d_index(va)]);
		ok = ok && lkm2_cp_table_matches(entry, (uintptr_t)pud);
	}} else if (pgtable_l4_enabled) {{
		ok = lkm2_cp_table_matches(entry, (uintptr_t)pud);
	}} else {{
		ok = lkm2_cp_table_matches(entry, (uintptr_t)pmd);
	}}
	if (pgtable_l4_enabled) {{
		entry = pud_val(pud[pud_index(va)]);
		ok = ok && lkm2_cp_table_matches(entry, (uintptr_t)pmd);
	}}
	*path_ok = ok;
	return pmd_val(pmd[pmd_index(va)]);
}}

static struct lkm2_cp_kernel __init lkm2_cp_observe_kernel(void)
{{
	uint64_t mode = satp_mode >> SATP_MODE_SHIFT;
	struct lkm2_cp_kernel result = {{
		.kernel_va = kernel_map.virt_addr,
		.kernel_pa = kernel_map.phys_addr,
		.page_offset = kernel_map.page_offset,
		.kernel_va_pa_offset = kernel_map.va_kernel_pa_offset,
		.mode = mode,
		.levels = pgtable_l5_enabled ? 5 : (pgtable_l4_enabled ? 4 : 3),
		.top_shift = pgtable_l5_enabled ? PGDIR_SHIFT :
			(pgtable_l4_enabled ? P4D_SHIFT : PUD_SHIFT),
	}};

	return result;
}}

static struct lkm2_cp_trampoline __init lkm2_cp_observe_trampoline(void)
{{
	uint64_t path_ok, leaf = lkm2_cp_walk(trampoline_pg_dir, trampoline_p4d,
					      trampoline_pud, trampoline_pmd,
					      kernel_map.virt_addr, &path_ok);
	struct lkm2_cp_trampoline result = {{
		.mode = satp_mode >> SATP_MODE_SHIFT,
		.va = kernel_map.virt_addr,
		.pa = lkm2_cp_pte_pa(leaf),
		.size = PMD_SIZE,
		.flags = lkm2_cp_pte_flags(leaf),
		.path_ok = path_ok,
	}};

	return result;
}}

static struct lkm2_cp_early_kernel __init lkm2_cp_observe_early_kernel(void)
{{
	uintptr_t va, end = kernel_map.virt_addr + kernel_map.size;
	uint64_t first_path, first = lkm2_cp_walk(early_pg_dir, early_p4d, early_pud,
						  early_pmd, kernel_map.virt_addr,
						  &first_path);
	bool coverage_ok = first_path;

	for (va = kernel_map.virt_addr; va < end; va += PMD_SIZE) {{
		uint64_t path_ok, leaf = lkm2_cp_walk(early_pg_dir, early_p4d,
						       early_pud, early_pmd, va,
						       &path_ok);
		uint64_t expected_pa = kernel_map.phys_addr + (va - kernel_map.virt_addr);

		coverage_ok = coverage_ok && path_ok && lkm2_cp_pte_pa(leaf) == expected_pa &&
			lkm2_cp_pte_flags(leaf) == pgprot_val(PAGE_KERNEL_EXEC);
	}}
	return (struct lkm2_cp_early_kernel) {{
		.mode = satp_mode >> SATP_MODE_SHIFT,
		.va = kernel_map.virt_addr,
		.pa = lkm2_cp_pte_pa(first),
		.flags = lkm2_cp_pte_flags(first),
		.coverage_ok = coverage_ok,
	}};
}}

static struct lkm2_cp_early_dtb __init lkm2_cp_observe_early_dtb(void)
{{
	uintptr_t fix_va = __fix_to_virt(FIX_FDT);
	uint64_t path0, path1;
	uint64_t leaf0 = lkm2_cp_walk(early_pg_dir, fixmap_p4d, fixmap_pud,
					      fixmap_pmd, fix_va, &path0);
	uint64_t leaf1 = lkm2_cp_walk(early_pg_dir, fixmap_p4d, fixmap_pud,
					      fixmap_pmd, fix_va + PMD_SIZE, &path1);
	uint64_t expected_pa = dtb_early_pa & PMD_MASK;
	bool coverage_ok = path0 && path1 && lkm2_cp_pte_pa(leaf0) == expected_pa &&
		lkm2_cp_pte_pa(leaf1) == expected_pa + PMD_SIZE &&
		lkm2_cp_pte_flags(leaf0) == pgprot_val(PAGE_KERNEL) &&
		lkm2_cp_pte_flags(leaf1) == pgprot_val(PAGE_KERNEL);

	return (struct lkm2_cp_early_dtb) {{
		.mode = satp_mode >> SATP_MODE_SHIFT,
		.dtb_pa = dtb_early_pa,
		.dtb_va = (uintptr_t)dtb_early_va,
		.fix_va = fix_va,
		.leaf0_pa = lkm2_cp_pte_pa(leaf0),
		.leaf0_flags = lkm2_cp_pte_flags(leaf0),
		.leaf1_pa = lkm2_cp_pte_pa(leaf1),
		.leaf1_flags = lkm2_cp_pte_flags(leaf1),
		.size = 2 * PMD_SIZE,
		.coverage_ok = coverage_ok,
	}};
}}

{milestones}
"""


def render_linux_handler(checkpoints: tuple[Checkpoint, ...]) -> str:
    lines = [
        "// SPDX-License-Identifier: GPL-2.0-only",
        "/* @generated by lkm2 checkpointgen; fixed raw SBI DBCN handler. */",
        "#include <linux/types.h>",
        "",
        "#define LKM2_SBI_EXT_DBCN 0x4442434eUL",
        "#define LKM2_SBI_DBCN_WRITE_BYTE 2UL",
        "",
        "static void lkm2_cp_write_byte(uint8_t byte)",
        "{",
        '\tregister unsigned long a0 asm ("a0") = byte;',
        '\tregister unsigned long a1 asm ("a1") = 0;',
        '\tregister unsigned long a6 asm ("a6") = LKM2_SBI_DBCN_WRITE_BYTE;',
        '\tregister unsigned long a7 asm ("a7") = LKM2_SBI_EXT_DBCN;',
        "",
        '\tasm volatile ("ecall" : "+r" (a0), "+r" (a1), "+r" (a6), "+r" (a7) :: "memory");',
        "}",
        "",
        "static void lkm2_cp_write_bytes(const char *bytes)",
        "{",
        "\twhile (*bytes)",
        "\t\tlkm2_cp_write_byte(*bytes++);",
        "}",
        "",
        "static void lkm2_cp_write_hex(uint64_t value)",
        "{",
        '\tstatic const char digits[] = "0123456789abcdef";',
        "\tint shift;",
        "",
        "\tfor (shift = 60; shift >= 0; shift -= 4)",
        "\t\tlkm2_cp_write_byte(digits[(value >> shift) & 0xf]);",
        "}",
        "",
        _render_c_declarations(checkpoints),
    ]
    for item in checkpoints:
        args = ", ".join(f"arg{index}" for index, _ in enumerate(item.parameters))
        lines.extend(
            [
                "",
                f"void {item.symbol}({_c_parameters(item)})",
                "{",
                f'\tlkm2_cp_write_bytes("LKMCP1 id={item.canonical_id} hash={item.hash16}");',
            ]
        )
        for index, parameter in enumerate(item.parameters):
            lines.append(f'\tlkm2_cp_write_bytes(" {parameter}=0x");')
            lines.append(f"\tlkm2_cp_write_hex(arg{index});")
        if not args:
            pass
        lines.extend(["\tlkm2_cp_write_byte('\\n');", "}"])
    return "\n".join(lines) + "\n"


def _replace_once(source: str, old: str, new: str, label: str) -> str:
    count = source.count(old)
    if count != 1:
        raise CheckpointGenerationError(
            f"sibling anchor {label!r} occurs {count} times instead of once"
        )
    return source.replace(old, new, 1)


def _modify_init(source: str) -> str:
    source = _replace_once(
        source,
        "#endif\n\nasmlinkage void __init setup_vm(uintptr_t dtb_pa)\n{",
        '#endif\n\n#include "lkm2_checkpoints.inc"\n\nasmlinkage void __init setup_vm(uintptr_t dtb_pa)\n{',
        "checkpoint include",
    )
    source = _replace_once(
        source,
        "\tapply_early_boot_alternatives();\n\tpt_ops_set_early();",
        "\tlkm2_checkpoint_kernel_map_ready();\n\tlkm2_checkpoint_preset_complete();\n\n"
        "\tapply_early_boot_alternatives();\n\tpt_ops_set_early();",
        "kernel map ready",
    )
    source = _replace_once(
        source,
        "#endif\n\n\t/*\n\t * Setup early PGD covering entire kernel",
        "#endif\n\tlkm2_checkpoint_trampoline_ready();\n\n\t/*\n\t * Setup early PGD covering entire kernel",
        "trampoline ready",
    )
    source = _replace_once(
        source,
        "\tcreate_kernel_page_table(early_pg_dir, true);\n\n\t/* Setup early mapping for FDT early scan */",
        "\tcreate_kernel_page_table(early_pg_dir, true);\n"
        "\tlkm2_checkpoint_early_kernel_ready();\n\n\t/* Setup early mapping for FDT early scan */",
        "early kernel ready",
    )
    source = _replace_once(
        source,
        "\tcreate_fdt_early_page_table(__fix_to_virt(FIX_FDT), dtb_pa);\n\n\t/*\n\t * Bootime fixmap",
        "\tcreate_fdt_early_page_table(__fix_to_virt(FIX_FDT), dtb_pa);\n"
        "\tlkm2_checkpoint_early_dtb_ready();\n"
        "\tlkm2_checkpoint_setup_complete();\n\n\t/*\n\t * Bootime fixmap",
        "early DTB and setup complete",
    )
    return source


def _modify_makefile(source: str) -> str:
    source = _replace_once(
        source,
        "CFLAGS_init.o := -mcmodel=medany\n",
        "CFLAGS_init.o := -mcmodel=medany\n"
        "CFLAGS_lkm2_checkpoint_handler.o := -mcmodel=medany\n",
        "handler code model",
    )
    source = _replace_once(
        source,
        "CFLAGS_init.o += -fno-pie\n",
        "CFLAGS_init.o += -fno-pie\n"
        "CFLAGS_lkm2_checkpoint_handler.o += -fno-pie\n",
        "handler relocatable flags",
    )
    source = _replace_once(
        source,
        "CFLAGS_REMOVE_init.o = $(CC_FLAGS_FTRACE)\n",
        "CFLAGS_REMOVE_init.o = $(CC_FLAGS_FTRACE)\n"
        "CFLAGS_REMOVE_lkm2_checkpoint_handler.o = $(CC_FLAGS_FTRACE)\n",
        "handler ftrace flags",
    )
    source = _replace_once(
        source,
        "KCOV_INSTRUMENT_init.o := n\n",
        "KCOV_INSTRUMENT_init.o := n\n"
        "KCOV_INSTRUMENT_lkm2_checkpoint_handler.o := n\n"
        "KASAN_SANITIZE_lkm2_checkpoint_handler.o := n\n"
        "KCSAN_SANITIZE_lkm2_checkpoint_handler.o := n\n",
        "handler instrumentation",
    )
    source = _replace_once(
        source,
        "obj-y += init.o\n",
        "obj-y += init.o lkm2_checkpoint_handler.o\n",
        "handler object",
    )
    return source


def _diff_file(path: str, before: str, after: str) -> str:
    return "".join(
        difflib.unified_diff(
            before.splitlines(keepends=True),
            after.splitlines(keepends=True),
            fromfile=f"a/{path}",
            tofile=f"b/{path}",
        )
    )


def _diff_new_file(path: str, content: str) -> str:
    lines = content.splitlines(keepends=True)
    return "".join(
        difflib.unified_diff(
            [], lines, fromfile="/dev/null", tofile=f"b/{path}"
        )
    )


def generate_sibling_patch(
    sibling: Path,
    mapping: CheckpointMapping,
    checkpoints: tuple[Checkpoint, ...],
) -> str:
    validate_sibling(sibling, mapping)
    init_path = "arch/riscv/mm/init.c"
    makefile_path = "arch/riscv/mm/Makefile"
    init_before = (sibling / init_path).read_text(encoding="utf-8")
    makefile_before = (sibling / makefile_path).read_text(encoding="utf-8")
    init_after = _modify_init(init_before)
    makefile_after = _modify_makefile(makefile_before)
    include_path = "arch/riscv/mm/lkm2_checkpoints.inc"
    handler_path = "arch/riscv/mm/lkm2_checkpoint_handler.c"
    return (
        _diff_file(makefile_path, makefile_before, makefile_after)
        + _diff_file(init_path, init_before, init_after)
        + _diff_new_file(include_path, render_linux_include(checkpoints, mapping))
        + _diff_new_file(handler_path, render_linux_handler(checkpoints))
    )
